spring.application.name=brindes-manager-api

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/brindesdb
spring.datasource.username=brindes
spring.datasource.password=brindes
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

app.jwt.secret=brindes-manager-api-secret-key-local-development-precisa-ter-tamanho-grande-123456789
app.jwt.expiration-ms=86400000